CREATE TABLE SDN_NAME(
  UID INTEGER PRIMARY KEY,
  NAME VARCHAR(255),
  SDN_TYPE VARCHAR(64),
  PROGRAM VARCHAR(64),
  TITLE VARCHAR(255),
  VESSEL_CALL_SIGN VARCHAR(64),
  VESSEL_TYPE VARCHAR(255),
  VESSEL_TONNAGE FLOAT,
  VESSEL_GROSS_REGISTERED_TONNAGE FLOAT,
  VESSEL_FLAG VARCHAR(64),
  VESSEL_OWNER VARCHAR(255),
  INFO VARCHAR(1024)
) AS SELECT * FROM CSVREAD(
  'src/main/resources/META-INF/database/sdn_names.csv',
  'UID,NAME,SDN_TYPE,PROGRAM,TITLE,VESSEL_CALL_SIGN,VESSEL_TYPE,VESSEL_TONNAGE,VESSEL_GROSS_REGISTERED_TONNAGE,VESSEL_FLAG,VESSEL_OWNER,INFO'
);

CREATE TABLE SDN_ADDRESS(
  ENTITY_UID INTEGER,
  ADDRESS_UID INTEGER PRIMARY KEY,
  ADDRESS VARCHAR(255),
  CITY VARCHAR(255),
  COUNTRY VARCHAR(64),
  EXT VARCHAR(255),
  FOREIGN KEY(ENTITY_UID) REFERENCES SDN_NAME(UID)
) AS SELECT * FROM CSVREAD(
  'src/main/resources/META-INF/database/sdn_addresses.csv',
  'ENTITY_UID,ADDRESS_UID,ADDRESS,CITY,COUNTRY,EXT'
);

CREATE TABLE SDN_ALTERNATE_NAME(
  ENTITY_UID INTEGER,
  ALTERNATE_NAME_UID INTEGER PRIMARY KEY,
  TYPE VARCHAR(64),
  NAME VARCHAR(255),
  FOREIGN KEY(ENTITY_UID) REFERENCES SDN_NAME(UID)
) AS SELECT * FROM CSVREAD(
  'src/main/resources/META-INF/database/sdn_alternate_names.csv',
  'ENTITY_UID,ALTERNATE_NAME_UID,TYPE,NAME'
);

CREATE VIEW SDN_ENTITY
AS
SELECT
  SDN_NAME.UID AS ID,
  SDN_NAME.NAME AS NAME,
  SDN_ADDRESS.ADDRESS AS ADDRESS,
  SDN_ADDRESS.CITY AS CITY,
  SDN_ADDRESS.COUNTRY AS COUNTRY,
  SDN_ALTERNATE_NAME.NAME AS ALTERNATE_NAME
FROM
  SDN_NAME JOIN SDN_ADDRESS ON SDN_NAME.UID = SDN_ADDRESS.ENTITY_UID
  JOIN SDN_ALTERNATE_NAME ON SDN_NAME.UID = SDN_ALTERNATE_NAME.ENTITY_UID;
