CREATE TABLE SDN_NAMES(
  UID INTEGER PRIMARY KEY,
  NAME VARCHAR(255),
  SDN_TYPE VARCHAR(64),
  PROGRAM VARCHAR(64),
  TITLE VARCHAR(255),
  VESSEL_CALL_SIGN VARCHAR(64),
  VESSEL_TYPE VARCHAR(255),
  VESSEL_TONNAGE FLOAT,
  VESSEL_GROSS_REGISTERED_TONNAGE FLOAT,
  VESSEL_FLAG VARCHAR(64),
  VESSEL_OWNER VARCHAR(255),
  INFO VARCHAR(1024)
) AS SELECT * FROM CSVREAD(
  'src/main/resources/META-INF/database/sdn_names.csv',
  'UID,NAME,SDN_TYPE,PROGRAM,TITLE,VESSEL_CALL_SIGN,VESSEL_TYPE,VESSEL_TONNAGE,VESSEL_GROSS_REGISTERED_TONNAGE,VESSEL_FLAG,VESSEL_OWNER,INFO'
);

CREATE TABLE SDN_ADDRESSES(
  ENTITY_UID INTEGER,
  ADDRESS_UID INTEGER PRIMARY KEY,
  ADDRESS VARCHAR(255),
  CITY VARCHAR(255),
  COUNTRY VARCHAR(64),
  EXT VARCHAR(255),
  FOREIGN KEY(ENTITY_UID) REFERENCES SDN_NAMES(UID)
) AS SELECT * FROM CSVREAD(
  'src/main/resources/META-INF/database/sdn_addresses.csv',
  'ENTITY_UID,ADDRESS_UID,ADDRESS,CITY,COUNTRY,EXT'
);

CREATE TABLE SDN_ALTERNATE_NAMES(
  ENTITY_UID INTEGER,
  ALTERNATE_NAME_UID INTEGER PRIMARY KEY,
  TYPE VARCHAR(64),
  NAME VARCHAR(255),
  FOREIGN KEY(ENTITY_UID) REFERENCES SDN_NAMES(UID)
) AS SELECT * FROM CSVREAD(
  'src/main/resources/META-INF/database/sdn_alternate_names.csv',
  'ENTITY_UID,ALTERNATE_NAME_UID,TYPE,NAME'
);

