CREATE TABLE SDN_NAMES(
  UID INTEGER PRIMARY KEY,
  NAME VARCHAR(255),
  SDN_TYPE VARCHAR(64),
  PROGRAM VARCHAR(64),
  TITLE VARCHAR(255),
  VESSEL_CALL_SIGN VARCHAR(64),
  VESSEL_TYPE VARCHAR(255),
  VESSEL_TONNAGE FLOAT,
  VESSEL_GROSS_REGISTERED_TONNAGE FLOAT,
  VESSEL_FLAG VARCHAR(64),
  VESSEL_OWNER VARCHAR(255),
  INFO VARCHAR(1024)
) AS SELECT * FROM CSVREAD(
  'src/main/resources/META-INF/database/sdn_names.csv',
  'UID,NAME,SDN_TYPE,PROGRAM,TITLE,VESSEL_CALL_SIGN,VESSEL_TYPE,VESSEL_TONNAGE,VESSEL_GROSS_REGISTERED_TONNAGE,VESSEL_FLAG,VESSEL_OWNER,INFO'
);